spring:
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    kim.nzxy.robin: debug
robin:
  validator:
    sustain:
      # 普通ip策略, 适用于一般接口, 能在连续的2个5s访问
      ip-normal:
        basic:
          lock-duration: 5s
          as-default: false
        expand:
          time-frame-size: 5s
          max-times: 2
      # 敏感接口ip策略, 只能在连续的1个5s访问
      ip-sensitive:
        basic:
          lock-duration: 5s
          as-default: false
        expand:
          time-frame-size: 5s
          max-times: 1
server:
  port: 9999