server:
  port: 9999

spring:
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    kim.nzxy.robin: debug
robin:
  validator:
    sustain:
      # 常规接口
      - topic: ip-normal
        lock-duration: 5s
        as-default: true
        time-frame-size: 5s
        max-times: 2
        precedence: 0
        metadata-handler: ip
        digest: ipv4-num64
      # 敏感接口
      - topic: ip-sensitive
        lock-duration: 5s
        as-default: false
        time-frame-size: 5s
        max-times: 1
        metadata-handler: ip
        digest: ipv4-num64
    bucket:
      # 特殊接口, 每分钟只能提交一次数据
      - topic: api-sensitive
        lock-duration: 10s
        as-default: false
        metadata-handler: uri
        capacity: 1
        generation-interval: 1m
        token-count: 1
        digest: hashcode64
