spring:
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    kim.nzxy.robin: debug
robin:
  validator:
    sustain:
      - topic: ip-normal
        lock-duration: 5s
        as-default: true
        time-frame-size: 5s
        max-times: 5
        precedence: 0
        metadata-handler: ip
      - topic: ip-sensitive
        lock-duration: 5s
        as-default: false
        time-frame-size: 5s
        max-times: 1
        metadata-handler: ip

server:
  port: 9999