spring:
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    kim.nzxy.robin: debug
robin:
  validator:
    sustain:
      ip:
        basic:
          lock-duration: 10s
          as-default: true
        config:
          time-frame-size: 10s
          max-times: 1
      referer:
        basic:
          lock-duration: 10s
          as-default: true
        config:
          time-frame-size: 10s
          max-times: 1
    bucket:
      ip-b:
        basic:
          lock-duration: 10s
          as-default: true
server:
  port: 9999