spring:
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    kim.nzxy.robin: debug
robin:
  validator:
    sustain:
      # 普通ip策略, 适用于一般接口
      ip-normal:
        basic:
          lock-duration: 10s
          as-default: true
        expand:
          time-frame-size: 10s
          max-times: 100
      #

server:
  port: 9999