spring:
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    kim.nzxy.robin: debug
robin:
  validator:
    sustain:
      ip:
        basic:
          lock-duration: 10s
      referer:
        basic:
          lock-duration: 10s
    bucket:
      ip-b:
        basic:
          lock-duration: 10s
